### ISSUE TITLE
ValueError: All input arrays (x) should have the same number of samples. Got array shapes: [(2, 74), (2, 18), (32, 572)]

### ISSUE THREAD

**Issue by yu-cherish** [ruidan/Aspect-level-sentiment#5]
Hello, I have already run your program, and the error shown in the title appears when train.py runs the second args.epochs loop. I don't know why the number of all input array (x) samples has changed. I have been watching for a long time, but I can't find a mistake. Can you help me see why this is? Thank you

**Comment by utf001** [comment]
do you solve this problem?how do you do.Can you share your method?thank you very much.
